const lowerDisplay = document.querySelector(".lowerDisplay");
const allClear = document.querySelector("#clear");
const backSpace = document.querySelector("#backspace");
const percentage = document.querySelector("#percentage");
const division = document.querySelector("#division");
const seven = document.querySelector("#seven");
const eight = document.querySelector("#eight");
const nine = document.querySelector("#nine");
const multiply = document.querySelector("#multiply");
const four = document.querySelector("#four");
const five = document.querySelector("#five");
const six = document.querySelector("#six");
const minus = document.querySelector("#minus");
const one = document.querySelector("#one");
const two = document.querySelector("#two");
const three = document.querySelector("#three");
const plus = document.querySelector("#plus");
const doubleZero = document.querySelector("#doubleZero");
const zero = document.querySelector("#zero");
const dot = document.querySelector("#dot");
const equalsTo = document.querySelector("#equalsTo");
allClear.addEventListener("click", () => lowerDisplay.textContent = "");
backSpace.addEventListener("click", () => lowerDisplay.textContent = lowerDisplay.textContent.slice(0,-1));
percentage.addEventListener("click", () => lowerDisplay.textContent += "%");
division.addEventListener("click", () => lowerDisplay.textContent += "÷");
seven.addEventListener("click", () => lowerDisplay.textContent += "7");
eight.addEventListener("click", () => lowerDisplay.textContent += "8");
nine.addEventListener("click", () => lowerDisplay.textContent += "9");
multiply.addEventListener("click", () => lowerDisplay.textContent += "×");
four.addEventListener("click", () => lowerDisplay.textContent += "4");
five.addEventListener("click", () => lowerDisplay.textContent += "5");
six.addEventListener("click", () => lowerDisplay.textContent += "6");
minus.addEventListener("click", () => lowerDisplay.textContent += "-");
one.addEventListener("click", () => lowerDisplay.textContent += "1");
two.addEventListener("click", () => lowerDisplay.textContent += "2");
three.addEventListener("click", () => lowerDisplay.textContent += "3");
plus.addEventListener("click", () => lowerDisplay.textContent += "+");
doubleZero.addEventListener("click", () => lowerDisplay.textContent += "00");
zero.addEventListener("click", () => lowerDisplay.textContent += "0");
dot.addEventListener("click", () => lowerDisplay.textContent += ".");
document.addEventListener("keypress", (e) => lowerDisplay.textContent += e.key);